### ISSUE TITLE
MPI IO missing particle with more than 1 MPI rank

### ISSUE THREAD

**Issue by acavelan** [unibas-dmi-hpc/SPH-EXA#54]
In MPIFileutils.hpp, the code has a wrong assumption on the number of particles per node.

```
const size_t split = d.n / d.nrank;
const size_t remaining = d.n - d.nrank * split;

const MPI_Offset col = d.n * sizeof(double);
MPI_Offset offset = d.rank * split * sizeof(double);
if (d.rank == 0) offset += remaining * sizeof(double);
```

**Comment by jgphpc** [comment]
@acavelan can't reproduce, how many mpi ?

**Comment by acavelan** [comment]
2 MPI nodes are enough. You can use the script/plot.py to plot the data. The file has the right size, but you will see that (most of the time, but not always) particles are missing (nothing is displayed in some corner of the space).

**Comment by jgphpc** [comment]
see https://github.com/unibas-dmi-hpc/SPH-EXA_mini-app/issues/60 too
